### ISSUE TITLE
@example value get ignored when there is more than one word

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/swagger#1089]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When I set this in dto file, swagger docs prints `string`
```typescript
/**
   * Error message
   * @example 'Bad Request'
   */
```

But when I change it to `'BadRequest'` it is ok. Also in array type:

```typescript
/**
   * List of error messages
   * @example ["email must be an email"]
   */
  message: Array<string>;
```

## Expected behavior
To print the full string sentence instead of `string` word.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by vahidvdn** [comment]
@kamilmysliwiec 
Here is a simple reproduction: https://github.com/vahidvdn/typescript-starter

After running the project, go to /docs and you will see one API. Email is ok because there is no space, but the password's value is `string` instead of `word with space` (check test.dto.ts file)
If you change it to `word` it will work fine.
Please let me know if you see the issue.

**Comment by kamilmysliwiec** [comment]
Thanks! Fixed in 4.7.7

**Comment by vahidvdn** [comment]
@kamilmysliwiec Thank you, I appreciate it.

**Comment by vahidvdn** [comment]
@kamilmysliwiec Sorry, this issue is still there in array type. For example:

```typescript
/**
   * List of error messages
   * @example ['property test should not exist']
   */
  message: Array<string>;
```

It shows `string` instead of `property test should not exist`

**Comment by kamilmysliwiec** [comment]
Thanks for reporting. Just fixed. Please, install the latest version
