### ISSUE TITLE
Reflect-metadata required for Swagger to work.

### ISSUE THREAD

**Issue by petrogad** [nestjs/swagger#221]
## I'm submitting a...
<pre><code>
[ ] Regression
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Adding swagger per directions from [NestJS](https://docs.nestjs.com/recipes/swagger) website produces an error and prevents app from starting up:

```
/PATH/node_modules/@nestjs/common/decorators/core/optional.decorator.js:11
            const args = Reflect.getMetadata(constants_1.OPTIONAL_DEPS_METADATA, target) || [];
                                 ^
TypeError: Reflect.getMetadata is not a function
    at Optional (/PATH/node_modules/@nestjs/common/decorators/core/optional.decorator.js:11:34)
```

## Expected behavior
Server can startup just fine having swagger exist in all it's glory

## Minimal reproduction of the problem with instructions
I pulled the [01-cats-app](https://github.com/nestjs/nest/tree/master/sample/01-cats-app) example then updated the main.ts file to mimic that of the [Nest JS Swagger](https://docs.nestjs.com/recipes/swagger) instructions.
```js
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";

import { ApplicationModule } from "./app.module";
import { NestFactory } from "@nestjs/core";
import { ValidationPipe } from "@nestjs/common";

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.useGlobalPipes(new ValidationPipe());

  const options = new DocumentBuilder()
    .setTitle("Cats example")
    .setDescription("The cats API description")
    .setVersion("1.0")
    .addTag("cats")
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup("api", app, document);

  await app.listen(3000);
}
bootstrap();
```

## Environment
<pre><code>
Nest version: 6.0.4
 
For Tooling issues:
- Node version:10.14.1
- Platform:  Mac
</code></pre>

**Comment by petrogad** [comment]
FYI, If I place `import "reflect-metadata";` in my main.ts file, then also install the dev dependency of `swagger-ui-express` this starts to work.

I'm not sure why the extra import is needed but wanted to at least bring up the work around until this is found.

**Comment by beninja** [comment]
Hey @petrogad can you explain a bit further the work around to fix this issue ?
I place `import "reflect-metadata";` in my `main.ts` file and I put `es6-shim`, `mocha` and `phantom` (swagger-ui-express dev dependencies) in my project's dev dependencies but stil got
`TypeError: Reflect.getMetadata is not a function`

**Comment by DavisJaunzems** [comment]
I had similar issue, and  I had to install `swagger-ui-express` as the new documentation says (https://docs.nestjs.com/recipes/swagger)

**Comment by petrogad** [comment]
@beninja as @DavisJaunzems said, you need swagger-ui-express as a dependency not a dev dependency.  Reason being is you're importing `import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';` likely at the top of your main.ts file. This relies on swagger-ui-express, so even if you conditionally remove it, your import will still exist.

My main.ts looks like this:
```js
import 'dotenv/config';
import 'reflect-metadata';

import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

import { AppModule } from './app.module';
import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.useGlobalPipes(new ValidationPipe());

  const options = new DocumentBuilder()
    .setTitle("Cats example")
    .setDescription("The cats API description")
    .setVersion("1.0")
    .addTag("cats")
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup("api", app, document);

  await app.listen(3000);
}
bootstrap();
```

**Comment by petrogad** [comment]
My main question here is why the `import 'reflect-metadata';` is necessary, or if the docs need to be updated to inform users of it.

**Comment by DavisJaunzems** [comment]
i don't think you need to add `reflect-metadata`, as it works for me without adding it

**Comment by petrogad** [comment]
@DavisJaunzems I thought it was supposed to, however if I pull that cat example as noted above, I couldn't get it to work without doing that import.

**Comment by beninja** [comment]
@petrogad Thanks a lot it's working with `import 'reflect-metadata';` before `import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';`.

Anyhow it's not answering why we need to import reflect-metadata.

**Comment by arkraft** [comment]
Decorators are somewhat experimental in typescript right now. This import adds a polyfill for the experimental Metadata API to typescript.

https://www.typescriptlang.org/docs/handbook/decorators.html#metadata

**Comment by NenadJovicic** [comment]
When i have imports like this
```javascript
import { INestApplication } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { ExpressAdapter } from '@nestjs/platform-express';
import { DocumentBuilder, SwaggerDocument, SwaggerModule } from '@nestjs/swagger';
import * as express from 'express';
import * as core from 'express-serve-static-core';
import { ApplicationModule } from './app.module';
```

then i don't have to import this reflect metadata in`main.ts`
so, it could be it is included in `NestFactory` or some other package that is defined above

**Comment by kamilmysliwiec** [comment]
Fixed in 3.1.0

**Comment by BorntraegerMarc** [comment]
@kamilmysliwiec did you maybe forget to update NPM? I still see version 3.0.2 there as latest...

**Comment by kamilmysliwiec** [comment]
Oh, it seems that the build has failed. Fixed, thanks!
