### ISSUE TITLE
New swagger plugin errors with nest monorepo

### ISSUE THREAD

**Issue by gulaandrij** [nestjs/swagger#409]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

`nest start` fails with new swagger plugin
![image](https://user-images.githubusercontent.com/2658746/70138889-e8d06400-1699-11ea-843f-0bceaaaa4bd9.png)
## Expected behavior

app started

## Minimal reproduction of the problem with instructions

https://github.com/gulaandrij/nest-monorepo-swagger
steps:
```
yarn install
nest start
```
## Environment

<pre><code>
[System Information]
OS Version     : Linux 5.3
NodeJS Version : v13.1.0
YARN Version    : 1.19.2

[Nest Information]
platform-express version : 6.7.2
swagger version          : 4.0.2
common version           : 6.7.2
core version             : 6.7.2
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 4.0.3. Thanks for reporting!

**Comment by danhooper** [comment]
I'm still seeing this even on 4.03. I've forked the above repo with 4.0.3 and still see the issue:

https://github.com/danhooper/nest-monorepo-swagger

```
npm i
nest build
```

```
Starting type checking service...
Using 1 worker with 2048MB memory limit
/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/typescript/lib/typescript.js:95861
                throw e;
                ^

TypeError: Cannot read property 'text' of undefined
    at IdentifierObject.TokenOrIdentifierObject.getText (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/typescript/lib/typescript.js:130308:31)
    at Object.getDecoratorName (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/utils/ast-utils.js:88:65)
    at find.item (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/utils/plugin-utils.js:8:89)
    at Array.find (<anonymous>)
    at Object.getDecoratorOrUndefinedByNames (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/utils/plugin-utils.js:8:49)
    at ControllerClassVisitor.getStatusCodeIdentifier (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/visitors/controller-class.visitor.js:65:50)
    at ControllerClassVisitor.createStatusPropertyAssignment (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/visitors/controller-class.visitor.js:60:33)
    at ControllerClassVisitor.createDecoratorObjectLiteralExpr (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/visitors/controller-class.visitor.js:35:18)
    at ControllerClassVisitor.addDecoratorToNode (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/visitors/controller-class.visitor.js:27:22)
    at visitNode (/Users/hoopedc1/git/nest-monorepo-swagger/node_modules/@nestjs/swagger/dist/plugin/visitors/controller-class.visitor.js:16:29)
```

**Comment by gulaandrij** [comment]
still the same situation 
![image](https://user-images.githubusercontent.com/2658746/70155969-d8c97c00-16bb-11ea-81e9-c60d8f5a71f4.png)

**Comment by gulaandrij** [comment]
ping @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
My mistake. Please update once again @gulaandrij @danhooper. 4.0.4 should be fine

**Comment by gulaandrij** [comment]
@kamilmysliwiec I have added DTO and receive the same error. Repo updated

**Comment by danhooper** [comment]
4.0.4 seems to fix it for my use case. Thanks!

**Comment by danhooper** [comment]
Actually I spoke to soon. Once I enable the DTO option I started getting the same error as well.

**Comment by gulaandrij** [comment]
@kamilmysliwiec 4.0.6 still the same

**Comment by kamilmysliwiec** [comment]
Thanks for the quick feedback! Please, test with 4.0.7 :)

**Comment by gulaandrij** [comment]
@kamilmysliwiec test repo now working fine. But my main project still failing with this error
![image](https://user-images.githubusercontent.com/2658746/70219462-8638a000-174d-11ea-86af-23f4683f2ce6.png)
I'm trying to reproduce it on test repo now

**Comment by gulaandrij** [comment]
@kamilmysliwiec I found an issue. Looks like it fails when dto is in lib and I use it in my main app. Repo updated

**Comment by gulaandrij** [comment]
also, could you reopen this while it still failing?

**Comment by kamilmysliwiec** [comment]
Sure thing. @gulaandrij thanks for your commitment. I've just pushed another fix that should solve your issue.

**Comment by gulaandrij** [comment]
tnx, it fix firs start but got an error in watch mode. Steps to reproduce:
```
1. nest start --watch
2. add decorator @ApiResponse({status: 200}) in apps/swagger/src/app.controller.ts to trigger rebuild
```
repo updated

**Comment by gulaandrij** [comment]
![image](https://user-images.githubusercontent.com/2658746/70228432-074b6380-175d-11ea-8dd6-003936143b8b.png)

**Comment by kamilmysliwiec** [comment]
Thanks for the investigation, it takes forever 😄 Please, update to the latest version and let me know if you are still encountering this issue

**Comment by gulaandrij** [comment]
tnx, errors have gone

**Comment by zbeyens** [comment]
The same bug happens when using yarn workspaces (monorepo). I don't have a public reproduction but the structure is similar to this https://github.com/AMGAVentures/poc-monorepo-starter 

yarn workspaces enables us to use a single `node_modules` located at the root, but the nest app is at `packages/api`. 

By copy/pasting `node_modules/@nestjs/swagger` folder to the nest app folder `packages/api/node_modules`, it works again. Basically the bug seems to happen when `node_modules` is not in the same folder than the nest app folder.

**Comment by pethersonmoreno** [comment]
the error "cannot read property 'kind' of undefined" is present yet.

**Comment by pethersonmoreno** [comment]
I've just open a new Issue about it:

- https://github.com/nestjs/swagger/issues/513
