### ISSUE TITLE
Swagger plugin does not work for optional properties if strict mode of TypeScript is enabled

### ISSUE THREAD

**Issue by pkerschbaum** [nestjs/swagger#462]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
The OpenAPI Swagger plugin (https://docs.nestjs.com/recipes/swagger#plugin) does not work correctly if "strictNullChecks" is enabled for TypeScript.
If a DTO contains an optional property, the following error is thrown:
```
(node:15508) UnhandledPromiseRejectionWarning: Error: A circular dependency has been detected (property key: "myProperty"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
    at SchemaObjectFactory.createNotBuiltInTypeReference (C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:107:19)
    at SchemaObjectFactory.mergePropertyWithMetadata (C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:88:25)
    at C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:55:35
    at Array.map (<anonymous>)
    at SchemaObjectFactory.exploreModelSchema (C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:54:52)
    at C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:27:36
    at Array.map (<anonymous>)
    at SchemaObjectFactory.createFromModel (C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:17:27)
    at exports.exploreApiParametersMetadata (C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\explorers\api-parameters.explorer.js:32:55)
    at C:\data\TEMP\nest-repo\nest\sample\11-swagger\node_modules\@nestjs\swagger\dist\swagger-explorer.js:67:45
(node:15508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled 
with .catch(). (rejection id: 1)
(node:15508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior
No error should be thrown.

## Minimal reproduction of the problem with instructions

1. Clone ```git@github.com:nestjs/nest.git```
1. Open terminal in ```sample/11-swagger```
1. Run ```npm install```
1. Add ```"strictNullChecks": true``` to compilerOptions of tsconfig.json (or add ```"strict": true```)
1. Add an optional property to ```CreateCatDto```, e.g.:
```typescript
readonly myProperty?: string;
```
1. Run ```npm run start:debug``` --> error is thrown

## What is the motivation / use case for changing the behavior?
Use the OpenAPI Swagger plugin with Strict-Mode of TypeScript.

## Hints

- It seems like the debug mode of nestjs does not correctly re-compile on code changes, sometimes the error persists even if e.g. the property is removed. 
Thus, one has to delete the ```dist``` folder now and then to see changes.
- If ```@IsString()``` of the package ```class-validator``` is added to the property, the error disappears.

## Environment

<pre><code>
Nest version (of sample/11-swagger): 6.10.12

 
For Tooling issues:
- Node version: v12.4.0  
- Platform: Windows 

</code></pre>

**Comment by kamilmysliwiec** [comment]
This should be fixed in 4.1.4. Please, let me know if you face any issues.

**Comment by Doccrazy** [comment]
This does not appear to be fixed. I can still reproduce the issue by the steps listed above, and a similar use case fails in my project as well.
Using @nestjs/swagger 4.1.7

**Comment by kamilmysliwiec** [comment]
Please, create a separate issue with a repository that reproduces your issue
